### ISSUE TITLE
not install cinder-volumes

### ISSUE THREAD

**Issue by andruwa13** [tigerlinux/openstack-liberty-installer-ubuntu1404lts#1]
Hello my name is Andrew. Thank you for work. Installation on my server https://www.hetzner.de/de/hosting/produkte_vserver/cx40 not want to create "cinder-volumes" drive. Error Device / dev / sdc1 not found (or ignored by filtering). The Horizon cinder-volumes Down. When installing Devstask cinder-volumes working

```
pvcreate /dev/sda1
  Can't open /dev/sda1 exclusively.  Mounted filesystem?
```

**Comment by tigerlinux** [comment]
Hi there Andrew,

Glad to see you're using my OpenStack installer.

In my installer (kilo/liberty) you can choose 3 different backends for
Cinder: NFS, GlusterFS and LVMIsci. By default, LVM is "on"
(cinderconfiglvm="yes" in ./configs/main-config.rc) and assumes you already
have a "cinder-volumes" VG Created. The main readme, in the "cinder"
section, explains this clearly and even give you some sample commands to
create the VG.

Some installation tools (devstack and packstack) can create a loop device
in the case you does not have a cinder-volumes VG, but this is not an ideal
situation for a production server, so your options here are:

a.- If you don't want to use permanent storage (cinder block devices) just
install with "cinderconfiglvm="no" in the main-config.rc
b.- If you wan't cinder working with a LVM based volume, and you have the
free space, just create the "cinder-volumes" VG as the readme explain.
c.- If you wan't cinder working, but by the moment you have no free space
to create a cinder-volumes, just create a loop device and create over it
the cinder-volumes VG.
d.- You can use NFS or GlusterFS instead of LVMIsci if you have a NAS (with
at least NFS support) or another linux server with enough space to export a
glusterfs or nfs share.

Well there are your options. Let me know if you need further assistance.

One question (just for curiosity): What operating system are you using
??... Ubuntu or Centos ?

Best regards,

RRMP.-

On Wed, Apr 6, 2016 at 4:48 AM, 3_1_3_u notifications@github.com wrote:

> Hello my name is Andrew. Thank you for work. Installation on my server
> https://www.hetzner.de/de/hosting/produkte_vserver/cx40 not want to
> create "cinder-volumes" drive. Error Device / dev / sdc1 not found (or
> ignored by filtering). The Horizon cinder-volumes Down. When installing
> Devstask cinder-volumes working
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/1

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
Thanks for the answer, Ubuntu

**Comment by tigerlinux** [comment]
You're Welcomed !.

By the way, the "pvcreate" command is failing you because it seems you are
using a probably already mounted device. You should use a free device for
the pvcreate command. Again, if your server lack the free space, and you
want to use Cinder, create a loop device and mount over it the
"cinder-volumes" VG. Sample:

mkdir /var/my-cinder
cd /var/my-cinder
truncate -s 5G my-cinder.img
losetup loop0 /var/my-cinder/my-cinder.img
pvcreate /dev/loop0
vgcreate cinder-volumes /dev/loop0

That will create for you a 5GB cinder-volumes VG

remember to include the instruction "losetup loop0
/var/my-cinder/my-cinder.img" in your rc.local in order to make it survive
server reboots.

Best regards,

RRMP.-

On Wed, Apr 6, 2016 at 8:16 AM, 3_1_3_u notifications@github.com wrote:

> Thanks for the answer, Ubuntu
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/1#issuecomment-206353624

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
root@Ubuntu-1404-trusty-64-minimal ~ # mkdir /var/my-cinder
root@Ubuntu-1404-trusty-64-minimal ~ # cd /var/my-cinder
root@Ubuntu-1404-trusty-64-minimal /var/my-cinder # truncate -s 150G my-cinder.img
root@Ubuntu-1404-trusty-64-minimal /var/my-cinder # losetup loop0 /var/my-cinder/my-cinder.img
loop0: No such file or directory

work:
losetup /dev/loop0  /var/my-cinder/my-cinder.img

**Comment by tigerlinux** [comment]
Opsss..

Sorry my mistake. In Ubuntu you need to include /dev. Also, you need to
"modprobe loop" first too:

modprobe loop
losetup /dev/loop0 /var/my-cinder/my-cinder.img

The instructions I passed to you work OK in Centos 7, but in ubuntu you
need to "modprobe loop" first and use /dev/loop0 instead of "loop0".

Best regards,

RRMP.-

On Wed, Apr 6, 2016 at 8:37 AM, 3_1_3_u notifications@github.com wrote:

> root@Ubuntu-1404-trusty-64-minimal ~ # mkdir /var/my-cinder
> root@Ubuntu-1404-trusty-64-minimal ~ # cd /var/my-cinder
> root@Ubuntu-1404-trusty-64-minimal /var/my-cinder # truncate -s 150G
> my-cinder.img
> root@Ubuntu-1404-trusty-64-minimal /var/my-cinder # losetup loop0
> /var/my-cinder/my-cinder.img
> loop0: No such file or directory
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/1#issuecomment-206361430

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
Thank you very much, works
