### ISSUE TITLE
not work qemu

### ISSUE THREAD

**Issue by andruwa13** [tigerlinux/openstack-liberty-installer-ubuntu1404lts#2]
Hi, I have a problem with qemu. Tried to fix as [here](http://www.computingforgeeks.com/2016/02/how-fix-openstack-nova-error.html), it does not work.

**Comment by tigerlinux** [comment]
Hi there Andrew,

Is the server you are using capable of hardware virtualization, mean, has
kvm-intel support ?.

All nova related services are running ?

Best regards,

RRMP.-

On Fri, Apr 8, 2016 at 4:21 AM, 3_1_3_u notifications@github.com wrote:

> Hi, I have a problem with qemu. Tried to fix as here
> http://www.computingforgeeks.com/2016/02/how-fix-openstack-nova-error.html,
> it does not work.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
> kvm-intel support ?

modprobe kvm-intel
modprobe: ERROR: could not insert 'kvm_intel': Operation not supported
No, but qemu works.

> All nova related services are running ?

yes

server :

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Stepping:              1
CPU MHz:               1999.999
BogoMIPS:              3999.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0,1


*-cpu
          description: CPU
          product: Intel(R) Xeon(R) CPU E5-26xx (Sandy Bridge)
          vendor: Intel Corp.
          physical id: 400
          bus info: cpu@0
          version: pc-i440fx-2.5
          slot: CPU 0
          size: 2GHz
          capacity: 2GHz
          width: 64 bits
          capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp x86-64 constant_tsc rep_good nopl eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm arat xsaveopt
          configuration: cores=2 enabledcores=2 threads=1

```

install OpenStack:
https://farm2.staticflickr.com/1674/25707170523_05a758ceb3_o.png

**Comment by andruwa13** [comment]
nova:
https://farm2.staticflickr.com/1628/26038396450_989ab5a7e1_o.png

**Comment by tigerlinux** [comment]
Well that's weird,

My installer is designed to check if the CPU support virtualization or not,
and make the proper changes accordingly. It seems that, somehow, it
detected a "kvm capable" CPU, but the machine is not allowing kvm-intel.

Let's do something. Run the following commands, and send me the results:

First Command:

_grep -E 'svm|vmx' /proc/cpuinfo|uniq|wc -l_

Second command:

_dpkg -l | grep nova-compute_

I just want to determine if your server is reporting "real" hardware
virtualization. On question: Is that server physical or virtual ??

Best regards,

RRMP.-

On Fri, Apr 8, 2016 at 1:09 PM, 3_1_3_u notifications@github.com wrote:

> nova:
> https://farm2.staticflickr.com/1628/26038396450_989ab5a7e1_o.png
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-207531607

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
Thank you for the answer

grep -E 'svm|vmx' /proc/cpuinfo|uniq|wc -l

> 0

 dpkg -l | grep nova-compute

> ii  nova-compute                       2:12.0.1-0ubuntu1~cloud0              all          OpenStack Compute - compute node base
> ii  nova-compute-libvirt               2:12.0.1-0ubuntu1~cloud0              all          OpenStack Compute - compute node libvirt support
> ii  nova-compute-qemu                  2:12.0.1-0ubuntu1~cloud0              all          OpenStack Compute - compute node (QEmu)

Server:
https://www.hetzner.de/hosting/produkte_vserver/cx40

**Comment by tigerlinux** [comment]
Well,

The good news is: The installer properly detected a non-kvm environment and
configured your Nova for qemu (not-kvm). The bad new is: It should work OK.
Something else is not allowing you to deploy instances and if it's not the
nova-compute, then is the neutron network.

Hard questions now:

Did you properly set-up your network environment ?.
Do you understand the different network models OpenStack uses ?.

On Fri, Apr 8, 2016 at 4:34 PM, 3_1_3_u notifications@github.com wrote:

> grep -E 'svm|vmx' /proc/cpuinfo|uniq|wc -l
> 
> 0
> 
> dpkg -l | grep nova-compute
> 
> ii nova-compute 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute - compute
> node base
> ii nova-compute-libvirt 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute -
> compute node libvirt support
> ii nova-compute-qemu 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute -
> compute node (QEmu)
> 
> Server:
> https://www.hetzner.de/hosting/produkte_vserver/cx40
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-207606317

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by tigerlinux** [comment]
Some extra questions:

How many ethernet interfaces have your server ?
Are you aware of the options for "external" network my installer supports
and the significance of those options ?

On Fri, Apr 8, 2016 at 5:52 PM, ANTICITIZEN ONE - (@) TIGER (@) LINUX (@) <
tigerlinux@gmail.com> wrote:

> Well,
> 
> The good news is: The installer properly detected a non-kvm environment
> and configured your Nova for qemu (not-kvm). The bad new is: It should work
> OK. Something else is not allowing you to deploy instances and if it's not
> the nova-compute, then is the neutron network.
> 
> Hard questions now:
> 
> Did you properly set-up your network environment ?.
> Do you understand the different network models OpenStack uses ?.
> 
> On Fri, Apr 8, 2016 at 4:34 PM, 3_1_3_u notifications@github.com wrote:
> 
> > grep -E 'svm|vmx' /proc/cpuinfo|uniq|wc -l
> > 
> > 0
> > 
> > dpkg -l | grep nova-compute
> > 
> > ii nova-compute 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute - compute
> > node base
> > ii nova-compute-libvirt 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute -
> > compute node libvirt support
> > ii nova-compute-qemu 2:12.0.1-0ubuntu1~cloud0 all OpenStack Compute -
> > compute node (QEmu)
> > 
> > Server:
> > https://www.hetzner.de/hosting/produkte_vserver/cx40
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-207606317
> 
> ## 
> 
> Saludos,
> 
> Reynaldo Martinez
> TigerLinux@Gmail.com

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
> Did you properly set-up your network environment ?.

no

> Do you understand the different network models OpenStack uses ?.

so-so

> How many ethernet interfaces have your server ?

https://farm2.staticflickr.com/1484/26253847011_a6ed800341_o.png

P.S. Sorry my bad English.

**Comment by tigerlinux** [comment]
Hi there Andrew,

Your English is OK. It's not my native language either (I'm from an
Spanish-talking country).

From what I see in the picture you've sent, your server only have one
Ethernet physical interface (probably virtual, bus the S/O sees as a
physical Ethernet eth0). That's not the best scenario, but it can be
managed.

Normally, what we (OpenStackers) do in such situations, is modify the eth0
to convert it in a switch-ovs-based interface, and attach the IP to it. In
this case you will have:

eth0: Physical interface, Ip not assigned
br-eth0: OpenV-Switch interface, IP assigned here

Then, in your openstack configuration the "physical" bridge will be br-eth0
and you'll have only one physical network where your external "virtual"
network will be configured. The external network is where the floating IP's
are located (if you are going to use gre/vxlan self-service tenant
networks). If you are just using flat networks, this "virtual" external
network will be your tenants network also.

The problem is, both schemes "need" an IP pool with enough addresses. Is
your server provider giving those IP's ?. If the answer is "no", then your
VM's (instances) inside OpenStack will lack external IP connectivity.

Now, I have to be honest with you: "So-so" is not enough for openstack. One
of the most complex things OpenStack have is the network model. The "main
failure factor" for anyone entering OpenStack arena, is the lack of proper
understanding of OpenStack networks. This is an area you need to master if
you wan't to really make progress on OpenStack !. In the "docs.openstack.org"
link, there are some documentations that explain those models (provider
networks, sef-service networks, flat, vlan, gre, vxlan). In the readme I
make a ver clear warning: "Read, read read and read again"... that's there
for a reason !.

So, my recommendations:

1.- First, learn about Openvswitch and how to properly configure it on
Ubuntu and Redhat based distros.
2.- Learn about the two main Network models used in openstack: Provider
networks, and, self-service networks.
3.- Learn why normally in provider networks flat and vlan are the most used
models, and learn why self-service networks need to be tunneled using
either gre or vxlan.
4.- Learn the difference between your "physical" network and your "virtual"
network.

Please now try to focus on understanding those topics (I know is a lot to
study, but is the right way to do it), and let me know If you have more
questions!. Remember: This is the most important topic in OpenStack and the
main failure reason !. Master this, and you'll tame the OpenStack monster !

Best regards,

RRMP.-

On Sat, Apr 9, 2016 at 1:27 AM, 3_1_3_u notifications@github.com wrote:

> Did you properly set-up your network environment ?.
> 
> no
> 
> Do you understand the different network models OpenStack uses ?.
> 
> so-so
> 
> How many ethernet interfaces have your server ?
> 
> https://farm2.staticflickr.com/1484/26253847011_a6ed800341_o.png
> 
> P.S. Sorry my bad English.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-207715608

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
thank you very much for your answers

**Comment by tigerlinux** [comment]
You're very welcome Andrew,

Success in your path to OpenStack mastering !!

Best regards,

RRMP.-

On Mon, Apr 11, 2016 at 8:44 AM, 3_1_3_u notifications@github.com wrote:

> thank you very much for your answers
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-208334218

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
it works now. It remains to understand why the message pops up
https://farm2.staticflickr.com/1519/26282610052_fbae4f8d99_o.png
and how to configure the SWIFT

**Comment by tigerlinux** [comment]
Hi there Andrew,

That message is an error introduced by one of ubuntu packages (sheepdog If
my memory serves me well). It happens only on ubuntu. The "centos" version
of those packages does not include the error.

You just need to find a file inside /etc/bash_completion.d directory and
comment it contents or just delete the file. The file name is sheepdog.

About swift... well... It's a world by itself. Again, the installer help's
you to configure a simple swift service based on just one drive or
partition, an from there you can expand it (manually) to a full cluster.

Because you are learning in a single server and surelly you don't have a
free partition, you can use the instructions I've sent to you earlier to
create a "loop" device, and mount the swift partition over it.

Please please please... read the main readme... the partition or disk must
be mounted with specific set of options in /etc/fstab, or swift will not
work.

Remember one thing: Swift is an Object Storage solution (not block device
permanent volumes solution like cinder). It is the equivalent of AWS S3.
If, by example, you are using trove (DBaaS) and want to include backups,
you "need" swift as trove backups require Object Storage. If you don't have
any other aplication for object storage, just forget swift until you master
the other OpenStack core components.

Best regards,

RRMP

NOTA: Are you from Germany ??

On Mon, Apr 11, 2016 at 3:05 PM, 3_1_3_u notifications@github.com wrote:

> it works now. It remains to understand why the message pops up
> https://farm2.staticflickr.com/1519/26282610052_fbae4f8d99_o.png
> and how to configure the SWIFT
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-208519541

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com

**Comment by andruwa13** [comment]
Thanks for the answer, no I'm from Ukraine

**Comment by tigerlinux** [comment]
Ok,

I'm from Caracas, Venezuela. Spanish-talking country.

Best regards,

RRMP.-

On Thu, Apr 14, 2016 at 9:01 AM, 3_1_3_u notifications@github.com wrote:

> Thanks for the answer, no I'm from Ukraine
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/tigerlinux/openstack-liberty-installer-ubuntu1404lts/issues/2#issuecomment-209941533

## 

Saludos,

Reynaldo Martinez
TigerLinux@Gmail.com
